[build-system]
requires = [
    "setuptools>=61.0",
    "amdsmi @ file:///opt/rocm-7.1.0/share/amd_smi"
]
build-backend = "setuptools.build_meta"

[project]
name = "wan"
version = "2.2.0"
description = "Wan: Open and Advanced Large-Scale Video Generative Models"
authors = [
    { name = "Wan Team", email = "wan.ai@alibabacloud.com" }
]
license = { file = "LICENSE.txt" }
readme = "README.md"
requires-python = "==3.13.8"
dependencies = [
    "torch @ file:///torch-2.9.1%2Brocm7.1.0.lw.git351ff442-cp313-cp313-linux_x86_64.whl",
    "flash_attn @ file:///root/flash_attn-2.8.3-py3-none-any.whl",
    "triton @ file:///triton-3.5.1%2Brocm7.1.0.gita272dfa8-cp313-cp313-linux_x86_64.whl",
    "torchaudio @ file:///torchaudio-2.9.0%2Brocm7.1.0.gite3c6ee2b-cp313-cp313-linux_x86_64.whl",
    "torchvision @ file:///torchvision-0.24.0%2Brocm7.1.0.gitb919bd0c-cp313-cp313-linux_x86_64.whl",
    "opencv-python>=4.9.0.80",
    "diffusers>=0.31.0",
    "transformers>=4.49.0",
    "tokenizers>=0.20.3",
    "accelerate>=1.1.1",
    "tqdm",
    "imageio",
    "easydict",
    "ftfy",
    "dashscope",
    "imageio-ffmpeg",
    "numpy>=1.23.5,<2",
    "decord",
    "librosa",
    "peft"
]

[project.optional-dependencies]
dev = [
    "pytest",
    "black",
    "flake8",
    "isort",
    "mypy",
    "huggingface-hub[cli]"
]
[tool.uv.extra-build-dependencies]
flash-attn = ["torch"]

[project.urls]
homepage = "https://wanxai.com"
documentation = "https://github.com/Wan-Video/Wan2.2"
repository = "https://github.com/Wan-Video/Wan2.2"
huggingface = "https://huggingface.co/Wan-AI/"
modelscope = "https://modelscope.cn/organization/Wan-AI"
discord = "https://discord.gg/p5XbdQV7"

[tool.setuptools]
packages = ["wan"]

[tool.setuptools.package-data]
"wan" = ["**/*.py"]

[tool.black]
line-length = 88

[tool.isort]
profile = "black"

[tool.mypy]
strict = true


